#!/bin/bash

path="e_engine_settings.c e_error_handler.c f_flags.c g_statemachine.c i_input.c i_inventory.c i_items.c l_asset_manager.c m_map.c m_map_tile.c main.c p_entity.c p_stats.c s_combat.c s_graphics.c s_menu.c t_config_tool.c t_gindex_tool.c t_strings.c w_window_manager.c"

gcc $(printf "src/%s " $path) -o game -lraylib -lm
