#pragma once

#define MAX_HOTBAR_SIZE 8
#define MAX_INV_SIZE 32
#define EMPTY_SLOT -1

#define LOOT_MAX_SIZE 64

#define ANIMATION_COUNT_INVALID -6890

#define INVALID_ENUM -8888
#define MAX_KEYS 4
#define NUMBER_OF_GAMEPADS_TO_CHECK 6

#define VALID_GEN_ID 1
#define MAX_KILLS_PER_FRAME 16

#define INVALID_CAP -808080 

#define NULL_INDX -1

